### ISSUE TITLE
Various requirements to meet

### ISSUE THREAD

**Issue by chrissexton** [IUS-CS/s22-project-tendies-movies#14]
* It looks like you may have had a start at the `/docs/architecture.md` file with `how-it-works.md`, but that file is empty. I'd appreciate a view about what your design structure is.
* Sprint 3 (due the day of this issue) should include some design pattern documentation as well. Be sure to get that in there.

**Comment by MrNuTTr** [comment]
`/doc/designpatterns.md` and `docs/sprint3.md` have been created and filled out.
